name: Build & Upload tux-dock

on: [push]

jobs:
  build:
    runs-on: [self-hosted-trixie]
    steps:
      - name: Manual clone
        run: |
          git clone https://mentalnet.xyz/forgejo/markmental/tuxdock.git .
          echo "✅ Repository cloned successfully"

      - name: Compile tux-dock
        run: |
          g++ -std=c++17 main.cpp -o tux-dock
          echo "🎉 tux-dock successfully compiled!"

      - name: Verify build
        run: file tux-dock

      - name: Package build as tar.gz
        run: |
          tar -czvf tux-dock-linux-x86_64.tar.gz tux-dock
          echo "📦 Created tux-dock-linux-x86_64.tar.gz"

      - name: Upload build artifact (tar.gz)
        uses: actions/upload-artifact@v3
        with:
          name: tux-dock-linux-x86_64-tar
          path: tux-dock-linux-x86_64.tar.gz

